### ISSUE TITLE
滑动手离开后惯性自动滚动时点击完成无法选择

### ISSUE THREAD

**Issue by iquejay** [Qymh/q-select#4]
1. 使用的是`q-select`还是`vue-q-select` 它们的版本号是多少~
q-select  v0.4.11
2. 发生bug的机型 麻烦具体到版本 如 ios12.1 或 安卓 7.0~
 chrome浏览器手机模拟环境
3. 请描述bug场景 如果可能的话可以贴上使用的代码~
滑动手离开后惯性自动滚动时点击完成无法选择，建议支持配置惯性系数来控制自动滑动的时间或点击完成时如果尚未滚动停止选择滑动到的最接近的值
thanks~

**Comment by Qymh** [comment]
之前做这里也有考虑过,最后决定还是和ios的选择是类似的
select滑动的时候点击了选择按钮,会自动重置到上一次选中的值的位置,这是专门去做的一个特性
包括如果在联动选择下,所有滑动动画未停止下,也不会更新子级联动,这也是一个专门做的特性,所以和滑动选择最近数据的逻辑相背

滑动系数的配置感觉用户很少会用到这个属性 最终的滑动效果也和滑动的动画时间也有关 给开发者配置可能挺不方便的 当初也研究过 现在的滑动到最后停止的时间是比ios本身少的 之前就是觉得停得太慢了 现在是相对ios本身的滑动提高了的 
@iquejay

**Comment by iquejay** [comment]
@Qymh 我试了一下，ios上面的原生滚动效果确实如你所说，那就保持不变好了。感受到了作者的用心，点赞。

**Comment by iquejay** [comment]
@Qymh 我试了一下，ios上面的原生滚动效果确实如你所说，那就保持不变好了。感受到了作者的用心，点赞。
