### ISSUE TITLE
模态层存在穿透以及移动端1px边框问题

### ISSUE THREAD

**Issue by jasonHG** [Qymh/q-select#5]
在模态层上面滑动的时候，下面内容也会滚动。在移动端边框会很粗，我看源码应该是border-bottom: 1px solid #ebebeb;导致的，移动端1px是不是应该处理一下？

**Comment by Qymh** [comment]
移动端1px可以有哈

模态层上面滑动指的是手指划到这个区域吗 @jasonHG 

![image](https://user-images.githubusercontent.com/29172211/82199606-7940ef00-9930-11ea-9378-8dd85ef2c6d1.png)

**Comment by jasonHG** [comment]
就是那个区域，移动端边框不处理看着会很粗啊。。

**Comment by Qymh** [comment]
移动端1px 0.4.13 加上了
手指滑到上面不失焦感觉会更好点喃 我看ios是用户离开屏幕后才失焦的

**Comment by jasonHG** [comment]
已解决，作者太用心了，点个赞！
